<?php

abstract class ContentKey
{
    // KEEP IN SYNC WITH JAVASCRIPT VALUES

    // GENERAL

    const CONTENT_KEY_NONE = 0;
    const CONTENT_KEY_LOGIN = 1;
    const CONTENT_KEY_HOME = 2;
    const CONTENT_KEY_ACCOUNT = 3;
    const CONTENT_KEY_TAGS = 5;
    const CONTENT_KEY_TAG = 7;
    const CONTENT_KEY_ACCOUNT_DETAILS = 10;
    const CONTENT_KEY_GEN_VALIDATION_TOKEN = 11;
    const CONTENT_KEY_VALIDATE_EMAIL_COMPLETE = 12;
    const CONTENT_KEY_NEEDS_VALIDATION = 13;
    const CONTENT_KEY_CHANGE_PASSWORD = 15;
    const CONTENT_KEY_CHANGE_EMAIL = 16;
    const CONTENT_KEY_NEW_SHARE = 17;
    const CONTENT_KEY_EDIT_SHARE = 18;
    const CONTENT_KEY_REGISTER_USER = 20;
    const CONTENT_KEY_FORGOT_PASSWORD = 21;
    const CONTENT_KEY_RESET_PASSWORD = 23;
    const CONTENT_KEY_PRIVACY = 24;
    const CONTENT_KEY_TERMS_OF_SERVICE = 25;
    const CONTENT_KEY_NEW_MEMO = 28;
    const CONTENT_KEY_EDIT_MEMO = 30;
    const CONTENT_KEY_MEMO_DETAILS = 31;
    const CONTENT_KEY_FIND = 34;
    const CONTENT_KEY_FRIENDS = 40;
    const CONTENT_KEY_FRIEND = 42;
    const CONTENT_KEY_SETTINGS = 50;
    const CONTENT_KEY_LOGOUT = 90;
    const CONTENT_KEY_HELP = 95;
    const CONTENT_KEY_ACCOUNT_LOCKED = 98;

    const CONTENT_KEY_DELETE_MEMO = 1050;
    const CONTENT_KEY_ALARM = 1130;
    const CONTENT_KEY_RENAME_TAG = 1240;
    const CONTENT_KEY_NOTIFICATIONS = 1370;

    const CONTENT_KEY_POST_LOGIN = 10001;
    const CONTENT_KEY_POST_ACCOUNT_DETAILS = 10010;
    const CONTENT_KEY_POST_CHANGE_EMAIL = 10016;
    const CONTENT_KEY_POST_REGISTER_USER = 10020;
    const CONTENT_KEY_POST_FORGOT_PASSWORD = 10021;
    const CONTENT_KEY_POST_NEW_MEMO = 10028;
    const CONTENT_KEY_POST_HIDE_MEMO = 10044;
    const CONTENT_KEY_POST_ALARM = 10070;
    const CONTENT_KEY_POST_CHANGE_PASSWORD = 10015;
    const CONTENT_KEY_ERROR = 11090;
    const CONTENT_KEY_REDIRECT = 12200;

    // ADMIN ONLY

    const CONTENT_KEY_ADMIN = 2112;
    const CONTENT_KEY_USERS = 20120;
    const CONTENT_KEY_LOGIN_AS = 20130;
    const CONTENT_KEY_DATA_CHECK = 20140;
    const CONTENT_KEY_SQL_OPS = 20150;
    const CONTENT_KEY_RUN_TESTS = 20170;
    const CONTENT_KEY_SECURITY_CHECK = 20180;
    const CONTENT_KEY_BATCH = 20190;

    const CONTENT_KEY_EASTER_EGG = 30010;
}
