<?php

abstract class ErrorCode
{
    const ERROR_NONE = 0;

    const ERROR_CONTENT_NOT_FOUND = 1005;

    const ERROR_INADEQUATE_AUTH_FOR_CONTENT = 1101;
    const ERROR_INADEQUATE_AUTH_FOR_SHARE = 1102;
    const ERROR_MEMO_NOT_VISIBLE = 1122;

    const ERROR_SHARE_NOT_FOUND = 1201;
    const ERROR_USER_NOT_AUTH_FOR_SHARE = 1202;
    const ERROR_FRIEND_NOT_FOUND = 1240;

    const ERROR_CONTENT_LOCAL_ONLY = 1307;

    const ERROR_INVALID_MEMO_ID = 1402;
    const ERROR_INVALID_BUCKET = 1415;

    const ERROR_TAG_NOT_FOUND = 1561;

    const ERROR_RENDER_ERROR = 1733;

    const ERROR_UNKNOWN_EXCEPTION = 2150;
    const ERROR_GENERAL = 2270;

    const ERROR_SAVING_ACCOUNT_DETAILS = 3187;

    const REDIRECT_CYCLE_ERROR = 3306;

    const ERROR_NEED_LOGIN = 6010;
    const ERROR_INADEQUATE_AUTH = 6050;
    const ERROR_INVALID_REDIRECT = 6080;
}