<?php

class Search
{
    const SPECIAL_SEARCH_NONE = 0;
    const SPECIAL_SEARCH_SHARED = 105;
    const SPECIAL_SEARCH_STARS = 110;
    const SPECIAL_SEARCH_UNSTARRED = 120;
    const SPECIAL_SEARCH_OLD = 130;
    const SPECIAL_SEARCH_EDITED = 140;
    const SPECIAL_SEARCH_BY_ME = 145;
    const SPECIAL_SEARCH_NOT_BY_ME = 150;
    const SPECIAL_SEARCH_PRIVATE = 160;
    const SPECIAL_SEARCH_ALARM = 170;
    const SPECIAL_SEARCH_OLDEST_FIRST = 180;
    const SPECIAL_SEARCH_HIDDEN = 190;
}