<?php

class CTermsOfService extends Content
{
    public function GetContentId()
    {
        return ContentKey::CONTENT_KEY_TERMS_OF_SERVICE;
    }

    public function AuthLevel()
    {
        return LoginStatus::ANY;
    }

    public function Render($userId)
    {
        $this->cacheable = self::CACHEABLE_ALWAYS;
        $this->suppressTips = self::SUPPRESS_TIPS_ALL;
        $this->needsEmailValSuppressed = true;

        $this->html =
            Html::Heading('Memofrog Terms of Service') .
            Html::P(self::GetNavLink('&lt;&nbsp;Back', Session::IsLoggedIn() ? ContentKey::CONTENT_KEY_HOME : ContentKey::CONTENT_KEY_LOGOUT)) .
            Html::Div('legal',
                Html::SubHeading('General terms') .
                Html::P("Memofrog provides services (&quot;Services&quot;) on the website at memofrog.com (the &quot;Site&quot;) subject to the following Terms of Service (as amended from time to time, the &quot;Terms of Service&quot;). We reserve the right, at our sole discretion, to change or modify portions of these Terms of Service at any time. We will post the changes and the date these terms were last revised on this page. Any such changes will become effective no earlier than seven (7) days after they are posted, except that changes addressing new functionality of the Services or changes made for legal reasons will become effective immediately. Your continued use of the Services after the date any such changes become effective constitutes your acceptance of the new Terms of Service.") .
                Html::SubHeading('Access and Use of the Services') .
                Html::P('<strong>Services Description</strong>: The Services are tools for for organizing and sharing ideas and notes.') .
                Html::P('<strong>Registration</strong>: You will be required to register an account with Memofrog in order to use certain features of the Services. If you choose to register, you agree to provide and maintain true, accurate, current and complete information about yourself on the Site&apos;s registration form. Registration data and other information you provide are governed by our ' . $this->GetNavLink('Privacy Policy', ContentKey::CONTENT_KEY_PRIVACY) . '. If you are under 18 years old, you may use the Site, with or without registering, only with the approval of your parent or guardian.') .
                Html::P('<strong>Member Account</strong>:  You are responsible for maintaining the confidentiality of your password and account, and are fully responsible for any and all activities that occur under your password or account. Memofrog will not be liable for any loss or damage arising from your failure to protect your account or password.') .
                Html::P('<strong>Modifications</strong>: Memofrog reserves the right to modify or discontinue any or all of the Services with or without notice. You agree that Memofrog will not be liable to you or to any third party for any modification, suspension or discontinuance of the Services.') .
                Html::P('<strong>Practices and Limits</strong>: You acknowledge that Memofrog may establish general practices and limits regarding the Services, including the time that data or other content will be retained by the Services and the storage space that will be used on Memofrog&apos;s servers for your account. You agree that Memofrog has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Services. You acknowledge that Memofrog reserves the right to terminate and delete accounts that remain inactive for an extended period of time. You further acknowledge that Memofrog reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.') .
                Html::SubHeading('Conditions of Use') .
                Html::P('<strong>User Conduct</strong>: You are solely responsible for all data or other materials (&quot;Content&quot;) that you post or use with the Services. Memofrog reserves the right to take legal action against anyone who, in Memofrog&apos;s sole discretion, violates this provision, including removing the offending content from the Services, suspending or terminating the account of such violators and reporting you to the law enforcement authorities. You agree to not use the Services to:') .
                Html::UL(
                    Html::LI( 'Upload any content that (i) infringes any intellectual property or other proprietary rights of Memofrog or any third party; (ii) poses or creates a privacy or security risk to anyone; (iii) constitutes unsolicited or unauthorized advertising or promotional materials, or any other form of solicitation; (iv) is unlawful, harmful, threatening, abusive, harassing, defamatory, obscene, hateful, pornographic, libelous, invasive of another&apos;s privacy, or (v) in the sole judgment of Memofrog, which restricts any other person from using the Services in any way, or which may expose Memofrog or its users to any harm or liability of any type;') .
                    Html::LI( 'Disrupt or interfere with the Services or servers or networks connected to the Site; or') .
                    Html::LI( 'Violate any applicable local, state, national or international law, or any regulations having the force of law;') .
                    Html::LI( 'Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;') .
                    Html::LI( 'Solicit personal information from anyone under the age of 18;') .
                    Html::LI( 'Harvest or collect email addresses or other contact information of other users from the Services by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;') .
                    Html::LI( 'Further or promote any criminal activity; or') .
                    Html::LI( 'Obtain any materials or information not intentionally made available through the Services.')) .
                /* Html::WrapTag('p', '<strong>Fees</strong>: If the Services or any portion thereof is made available for any fee, you will be required to select a payment plan and provide Memofrog information regarding your credit card or other payment instrument.  You represent and warrant to Memofrog that such information is true and that you are authorized to use the payment instrument.  You will promptly update your account information with any changes (for example, a change in your billing address or credit card expiration date) that may occur.  You agree to pay Memofrog the amount that is specified in the payment plan in accordance with the terms of such plan and this Terms of Service.  You hereby authorize Memofrog to bill your payment instrument in advance on a periodic basis in accordance with the terms of the applicable payment plan until you terminate your account, and you further agree to pay any charges so incurred. If you dispute any charges you must let Memofrog know within sixty (60) days after the date that Memofrog charges you.We reserve the right to change Memofrog&apos;s prices. If Memofrog does change prices, Memofrog will provide notice of the change on the Site or in email to you, at Memofrog&apos;s option, at least 30 days before the change is to take effect. Your continued use of the Services after the price change becomes effective constitutes your agreement to pay the changed amount. You shall be responsible for all taxes associated with the Services other than U.S. taxes based on Memofrog&apos;s net income.') . */
                Html::P('<strong>Commercial Use</strong>: Unless otherwise expressly authorized by Memofrog, you agree not to use, publish, copy, or transmit any portion of the Services.') .
                Html::SubHeading('Intellectual Property Rights') .
                Html::P('<strong>Content, Software and Trademarks</strong>: You acknowledge and agree that the Services may contain content or features that are protected by copyright, patent, trademark, trade secret or other proprietary rights and laws. Except as expressly authorized by Memofrog, you agree not to use, publish, copy, or transmit any portion of the Site or Services, in whole or in part, except that the foregoing does not apply to your own User Content (as defined below) that you legally upload to the Services. You will not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods on the Site. If you are blocked by Memofrog from accessing the Services (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address). Any use of the Services other than as specifically authorized herein is strictly prohibited. The technology and software used to provide the Site and Services are property of Memofrog, or our partners. Any rights not expressly granted herein are reserved by Memofrog.') .
                Html::P('The Memofrog name and logos are trademarks and service marks of Memofrog (collectively the &quot;Memofrog Trademarks&quot;). Other product and service names and logos used and displayed via the Services may be trademarks or service marks of other parties who may or may not be affiliated with or connected to Memofrog. Nothing in these Terms of Service or the Site or Services should be construed as granting, by any means, any license or right to use any of Memofrog trademarks displayed on the Site, without our prior written permission in each instance.') .
                Html::P('<strong>Third-Party Content: </strong>Under no circumstances will Memofrog be liable in any way for any content or materials of any third parties (including users), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. You acknowledge that Memofrog does not pre-screen content, but that Memofrog and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Services. Without limiting the foregoing, Memofrog and its designees will have the right to remove any content that violates these Terms of Service or is deemed by Memofrog, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content.') .
                Html::P('<strong>User Content: </strong> With respect to the content or other materials you upload through the Services or share with other users or recipients (collectively, &quot;User Content&quot;), you represent and warrant that you own all right, title and interest in and to such User Content, including, without limitation, all copyrights and rights of publicity contained therein.') .
                Html::P('You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Services provided by you to Memofrog are non-confidential and that Memofrog will be entitled to the unrestricted use and dissemination of this information for any purpose, commercial or otherwise, without acknowledgment or compensation to you.') .
                Html::P('You acknowledge and agree that Memofrog may preserve content and may also disclose content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms of Service; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Memofrog, its users and the public. You understand that the all features of the Services, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.') .
                Html::Heading('Third-Party Websites') .
                Html::P('The Services may provide, or third parties may provide, links or other access to other sites and resources on the Internet. Memofrog has no control over such sites and resources and Memofrog is not responsible for and does not endorse such sites and resources. You further acknowledge and agree that Memofrog will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site or resource. Any dealings you have with third parties found while using the Services are between you and the third party, and you agree that Memofrog is not liable for any loss or claim that you may have against any such third party.') .
                Html::Heading('Indemnity and Release') .
                Html::P('You agree to release, indemnify and hold Memofrog and its affiliates and their officers, employees, directors and agents harmless from any from any and all losses, damages, expenses, including reasonable attorneys&apos; fees, rights, claims, actions of any kind and injury from your use of the Site and Services.') .
                Html::Heading('Disclaimer of Warranties') .
                Html::P('YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS. MEMOFROG EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. MEMOFROG MAKES NO WARRANTY THAT (I) THE SERVICES WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS.') .
                Html::Heading('Limitation of Liability') .
                Html::P('YOU EXPRESSLY UNDERSTAND AND AGREE THAT MEMOFROG WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF MEMOFROG HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM: (I) THE USE OR THE INABILITY TO USE THE SERVICES; (II) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICES; (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICES; OR (V) ANY OTHER MATTER RELATING TO THE SERVICES. IN NO EVENT WILL MEMOFROG&apos;S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OF ACTION EXCEED THE AMOUNT YOU HAVE PAID MEMOFROG IN THE LAST SIX (6) MONTHS, OR, IF GREATER, TEN UNITED STATES DOLLARS ($10 USD).') .
                Html::P('SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICES OR WITH THESE TERMS OF SERVICES, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICES.') .
                Html::SubHeading('Arbitration') .
                Html::P('At Memofrog&apos;s or your election, all disputes, claims, or controversies arising out of or relating to the Terms of Service or the Services that are not resolved by mutual agreement may be resolved by binding arbitration to be conducted before JAMS (an arbitration service), or its successor. Unless otherwise agreed by the parties, arbitration will be held in San Mateo County, California before a single arbitrator mutually agreed upon by the parties, or if the parties cannot mutually agree, a single arbitrator appointed by JAMS, and will be conducted in accordance with the rules and regulations promulgated by JAMS unless specifically modified in the Terms of Service. The arbitration must commence within forty-five (45) days of the date on which a written demand for arbitration is filed by either party.  The arbitrator&apos;s decision and award will be made and delivered within sixty (60) days of the conclusion of the arbitration and within six (6) months of the selection of the arbitrator.  The arbitrator will not have the power to award damages in excess of the limitation on actual compensatory, direct damages set forth in the Terms of Service and may not multiply actual damages or award punitive damages or any other damages that are specifically excluded under the Terms of Service, and each party hereby irrevocably waives any claim to such damages. The arbitrator may, in his or her discretion, assess costs and expenses (including the reasonable legal fees and expenses of the prevailing part) against any party to a proceeding. Any party refusing to comply with an order of the arbitrators will be liable for costs and expenses, including attorneys&apos; fees, incurred by the other party in enforcing the award.  Notwithstanding the foregoing, in the case of temporary or preliminary injunctive relief, any party may proceed in court without prior arbitration for the purpose of avoiding immediate and irreparable harm.  The provisions of this arbitration section will be enforceable in any court of competent jurisdiction.') .
                Html::P('Notwithstanding the provisions of the introductory section above, if Memofrog changes this &apos;Arbitration&apos; section after the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service ), you may reject any such change by sending us written notice within 30 days of the date such change became effective, as indicated in the &quot;Revised&quot; date or in the date of Memofrog&apos;s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any dispute between you and Memofrog in accordance with the provisions of this section as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).') .
                Html::SubHeading('Termination') .
                Html::P('You agree that Memofrog, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Services and remove and discard any content within the Services, for any reason, including, without limitation, for lack of use or if Memofrog believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Services, may be referred to appropriate law enforcement authorities. Memofrog may also in its sole discretion and at any time discontinue providing the Services, or any part thereof, with or without notice. You agree that any termination of your access to the Services under any provision of this Terms of Service may be effected without prior notice, and acknowledge and agree that Memofrog may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Services. Further, you agree that Memofrog will not be liable to you or any third party for any termination of your access to the Services.') .
                Html::SubHeading('User Disputes') .
                Html::P('You agree that you are solely responsible for your interactions with any other user in connection with the Service and Memofrog will have no liability or responsibility with respect thereto.  Memofrog reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Services.') .
                Html::SubHeading('General') .
                Html::P('These Terms of Service constitute the entire agreement between you and Memofrog and govern your use of the Services, superseding any prior agreements between you and Memofrog with respect to the Service. You also may be subject to additional terms and conditions that may apply when you use affiliate or third party services, third party content or third party software. These Terms of Service will be governed by the laws of the State of California without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and Memofrog agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within San Francisco County, California. The failure of Memofrog to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision. If any provision of these Terms of Service is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms of Service remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or these Terms of Service must be filed within six (6) months after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You may not assign this Terms of Service without the prior written consent of Memofrog, but Memofrog may assign or transfer this Terms of Service, in whole or in part, without restriction. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Services may also provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the Services.') .
                Html::SubHeading('Privacy') .
                Html::P('For details about privacy please see the ' . $this->GetNavLink('Privacy Policy', ContentKey::CONTENT_KEY_PRIVACY) . '. By using the Services, you consent to our collection and use of personal data as outlined therein.') .
                Html::SubHeading('Contact') .
                Html::P('If you have any questions, complaints or claims with respect to Memofrog or the Services, or to report violations of these therms, please contact Memofrog at <a href="mailto:legal@memofrog.com">legal@memofrog.com</a>') .
				Html::TagWithClass('p', 'parenthetic', 'Revised November 2, 2015')
            );
    }
}